from pathlib import Path
root=Path.cwd();src=root/'frontend/src'; assert (src/'App.tsx').is_file(), 'Rode na pasta karaoke'
patches=[('ports/api.ts', 'export interface ApiPort {', 'export interface LyricsSuggestion { id: number; track_name: string; artist_name: string; duration: number | null; synced: boolean; plain: boolean; preview: string }\nexport interface LyricsRecord { status: string; content: string; source: string | null; external_id: string | null; lines: [number,string][] }\nexport interface ApiPort {'), ('ports/api.ts', '  diagnostics(): Promise<Diagnostics>;', '  diagnostics(): Promise<Diagnostics>;\n  lyricsSuggestions(id: string): Promise<LyricsSuggestion[]>;\n  selectedLyrics(id: string): Promise<LyricsRecord>;\n  chooseLyrics(id: string, recordId: number): Promise<LyricsRecord>;\n  importLrc(id: string, file: File): Promise<LyricsRecord>;'), ('adapters/httpApi.ts', '  diagnostics() { return this.json<never>("/api/library/diagnostics"); }', '  diagnostics() { return this.json<never>("/api/library/diagnostics"); }\n  lyricsSuggestions(id: string) { return this.json<import("../ports/api").LyricsSuggestion[]>(`/api/songs/${encodeURIComponent(id)}/lyrics/suggestions`); }\n  selectedLyrics(id: string) { return this.json<import("../ports/api").LyricsRecord>(`/api/songs/${encodeURIComponent(id)}/lyrics`); }\n  chooseLyrics(id: string, recordId: number) { return this.json<import("../ports/api").LyricsRecord>(`/api/songs/${encodeURIComponent(id)}/lyrics/lrclib/${recordId}`, {method:"PUT"}); }\n  importLrc(id: string, file: File) { const fd=new FormData();fd.append("file",file);return this.json<import("../ports/api").LyricsRecord>(`/api/songs/${encodeURIComponent(id)}/lyrics/import-lrc`,{method:"POST",body:fd}); }'), ('App.tsx', 'import { Library } from "./features/Library";', 'import { Library } from "./features/Library";\nimport { LyricsPage } from "./features/LyricsPage";'), ('App.tsx', 'type Tab = "buscar" | "fila" | "biblioteca" | "rede";', 'type Tab = "buscar" | "fila" | "biblioteca" | "letras" | "rede";'), ('App.tsx', '["buscar", "fila", "biblioteca", "rede"] : ["buscar", "fila", "biblioteca"]', '["buscar", "fila", "biblioteca", "letras", "rede"] : ["buscar", "fila", "biblioteca", "letras"]'), ('App.tsx', '      {tab === "rede" && isHost && <NetworkPanel api={api} />}', '      {tab === "letras" && <LyricsPage api={api} songs={list} isHost={isHost} refresh={() => void songs.reload()} />}\n      {tab === "rede" && isHost && <NetworkPanel api={api} />}')]
staged={}
for rel,old,new in patches:
    p=src/rel;s=staged.get(p,p.read_text(encoding='utf-8'))
    if new in s:continue
    if s.count(old)!=1:raise RuntimeError(f'Trecho diferente do esperado em {rel}: {old[:80]} (nenhuma alteracao feita)')
    staged[p]=s.replace(old,new)
assert (src/'features/LocalPreview.tsx').is_file(), 'Falta LocalPreview.tsx do modulo anterior; nenhuma alteracao feita'
for p,s in staged.items():p.write_text(s,encoding='utf-8')
(src/'features/LyricsPage.tsx').write_bytes((Path(__file__).resolve().parent/'frontend/src/features/LyricsPage.tsx').read_bytes())
print('Frontend de letras instalado. Rode cd frontend; npm test; npm run build')
