from enum import Enum

class State(str, Enum):
    AGUARDANDO_UPLOAD = "AGUARDANDO_UPLOAD"
    NA_FILA = "NA_FILA"
    PREPARANDO = "PREPARANDO"
    SEPARANDO_INSTRUMENTAL_VOCAIS = "SEPARANDO_INSTRUMENTAL_VOCAIS"
    SEPARANDO_LEAD_BACKING = "SEPARANDO_LEAD_BACKING"
    ANALISANDO = "ANALISANDO"
    CONCLUIDA = "CONCLUIDA"
    FALHA = "FALHA"
    CANCELADA = "CANCELADA"

S = State
ACTIVE = {S.PREPARANDO, S.SEPARANDO_INSTRUMENTAL_VOCAIS, S.SEPARANDO_LEAD_BACKING, S.ANALISANDO}
_RUN = {S.FALHA, S.CANCELADA}
TRANSITIONS = {
    S.AGUARDANDO_UPLOAD: {S.NA_FILA, S.CANCELADA},
    S.NA_FILA: {S.PREPARANDO, S.CANCELADA},
    S.PREPARANDO: {S.SEPARANDO_INSTRUMENTAL_VOCAIS} | _RUN,
    S.SEPARANDO_INSTRUMENTAL_VOCAIS: {S.SEPARANDO_LEAD_BACKING, S.ANALISANDO} | _RUN,
    S.SEPARANDO_LEAD_BACKING: {S.ANALISANDO} | _RUN,
    S.ANALISANDO: {S.CONCLUIDA} | _RUN,
    S.FALHA: {S.NA_FILA},
    S.CONCLUIDA: set(),
    S.CANCELADA: set(),
}
