from dataclasses import dataclass, field
from typing import Iterable, Protocol

@dataclass
class MediaInfo:
    duration_s: float
    formats: frozenset = field(default_factory=frozenset)
    codec: str = ""

class MediaValidator(Protocol):
    def probe(self, path, ext: str) -> MediaInfo: ...

class FileStore(Protocol):
    def free_bytes(self) -> int: ...
    def save_stream(self, song_id: str, chunks: Iterable[bytes], max_bytes: int): ...
    def commit(self, song_id: str, tmp, ext: str): ...
    def discard_tmp(self, song_id: str) -> None: ...
    def list_files(self, song_id: str) -> list[str]: ...
    def list_song_dirs(self) -> list[str]: ...
    def begin_delete(self, song_id: str): ...
    def finish_delete(self, token) -> bool: ...
    def rollback_delete(self, token) -> None: ...
    def purge_trash(self) -> int: ...
