from typing import Protocol
from ..domain.entities import Job, Song
from ..domain.states import State

class SongStore(Protocol):
    def create_song(self, title: str, artist: str, source_video_id: str | None) -> Song: ...
    def get_song(self, song_id: str) -> Song: ...
    def list_songs(self) -> list[Song]: ...

class JobQueue(Protocol):
    def enqueue(self, song_id: str, max_attempts: int) -> Job: ...
    def claim_next(self) -> Job | None: ...
    def advance(self, job_id: int, state: State, step: str = "", message: str = "") -> Job: ...
    def fail(self, job_id: int, error: str) -> Job: ...
    def cancel(self, job_id: int) -> Job: ...
    def retry(self, job_id: int) -> Job: ...
    def recover(self) -> list[Job]: ...
    def get_job(self, job_id: int) -> Job: ...
    def list_jobs(self) -> list[Job]: ...
    def position(self, job_id: int) -> int | None: ...
